### ISSUE TITLE
Is this bundle still maintained?

### ISSUE THREAD

**Issue by imikay** [dakatsuka/JBuilderBundle#1]
Hi, 

The last update of this bundle is 3 years ago, is this still maintained? We just upgraded our project to Symfony 3.0, this bundle needs an upgrade to work with Symfony.

An update would be much appreciated.

**Comment by dakatsuka** [comment]
@imikay 
I'm sorry. I'm not engaged in development using PHP and Symfony2 recently.
It takes a lot of time to fix this issue. :bow:

**Comment by dakatsuka** [comment]
@imikay Fixed :+1:

**Comment by imikay** [comment]
@dakatsuka That's awesome, thanks. :+1:
